windwaker/skyshaker/urls.py
from django.conf.urls import patterns, url, include
from skyshaker import views
from django.conf import settings

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^community-guidelines/$', views.community, name='community'),
    url(r'projects/(?P<slug>[^\./]+)$', views.project, name='project'),
    url(r'projects/(?P<slug>[^\./]+)/edit$', views.projectEdit, name='projectEdit'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profiles/(?P<slug>[^\./]+)$', views.profile, name='profile'),
    url(r'^profiles/(?P<slug>[^\./]+)/edit$', views.profileEdit, name='profileEdit'),
    url(r'^search/', views.search, name='search'),
    url(r'^contribute/$', views.contribute, name='contribute'),
    url(r'^makerspaces/$', views.makerspaces, name='makerspaces'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^team/$', views.team, name='team'),
    url(r'^donate/$', views.donate, name='donate'),
#    url(r'^geodream/$', views.geodream, name='geodream'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^geoboosts/$', views.geoboosts, name='geoboosts'),
    url(r'^geodreams/$', views.geodreams, name='geodreams'),
    url(r'^georecipes/$', views.georecipes, name='georecipes'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

windwaker/windwaker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from skyshaker import views
from django.conf import settings

urlpatterns = patterns('',
    url(r'^skyshaker/', include('skyshaker.urls')),
    url(r'^community-guidelines/$', views.community, name='community'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^donate/', views.donate, name='donate'),
    url(r'projects/(?P<slug>[^\./]+)$', views.project, name='project'),
    url(r'projects/(?P<slug>[^\./]+)/edit$', views.projectEdit, name='projectEdit'),
    url(r'^profiles/(?P<slug>[^\./]+)$', views.profile, name='profile'),
    url(r'^profiles/(?P<slug>[^\./]+)/edit$', views.profileEdit, name='profileEdit'),
    url(r'^search/', views.search, name='search'),
    url(r'^contribute/$', views.contribute, name='contribute'),
    url(r'^makerspaces/$', views.makerspaces, name='makerspaces'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^team/$', views.team, name='team'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^register/$', views.register, name='register'),
#    url(r'^geodream/$', views.geodream, name='geodream'),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^geoboosts/$', views.geoboosts, name='geoboosts'),
    url(r'^geodreams/$', views.geodreams, name='geodreams'),
    url(r'^georecipes/$', views.georecipes, name='georecipes'),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

windwaker/skyshaker/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.template.defaultfilters import slugify
import os, re




class Image(models.Model):
    image = models.ImageField(upload_to="images", null=True, blank=True)
    caption = models.CharField(max_length=200, null=True, blank=True)
    def __str__(self):
        return os.path.split(self.image.name)[1]

class Link(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['title']

class MakerSpace(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()
    state = models.CharField(max_length=200, null=True, blank=True)
    lat = models.DecimalField(max_digits=8, decimal_places=5, null=True, blank=True)
    lon = models.DecimalField(max_digits=8, decimal_places=5, null=True, blank=True)
    url = models.URLField(default="", null=True, blank=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

class Project(models.Model):
    owner = models.ForeignKey(User, null=True, blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, null=True, blank=True)
    abstract = models.TextField(null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    links = models.ManyToManyField('Link', blank=True)
    videos = models.ManyToManyField('Video', blank=True)
    images = models.ManyToManyField('Image', blank=True)
    rating = models.IntegerField(default='3',null=True, blank=True)
    ratingAsString = models.TextField(null=True, blank=True)
    typeOfProject = models.CharField(max_length=200,null=True, blank=True, choices=(("GeoDream","GeoDream"),("GeoRecipe","GeoRecipe"),("GeoBoost","GeoBoost")))
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, editable=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True, editable=True)
    related = models.ManyToManyField('self', blank=True)
    def __str__(self):
        if self.owner is None:
            return self.title
        elif self.owner.username != "":
            return self.title + " by " + self.owner.username



class Tag(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)

class UserProfile(models.Model):
    # This line is required.  Links UserProfile to a User model instance.
    user = models.OneToOneField(User, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    facebook = models.CharField(max_length=200, null=True, blank=True)
    twitter = models.CharField(max_length=200, null=True, blank=True)
    linkedin = models.CharField(max_length=200, null=True, blank=True)
    picture = models.ImageField(upload_to="images", null=True, blank=True, default=settings.STATIC_URL+"skyshaker/img/user/default.jpg")
    def __str__(self):
        return self.user.username

class Video(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    embed = models.TextField(default="",null=True,blank=True)
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['title']

class Resource(models.Model):
    typeOfResource = models.CharField(max_length=200,null=True, blank=True, choices=(("Mapping_and_Software","Mapping and Software"),("Hardware_and_Software","Hardware and Software"),("Maker_Resources","Maker Resources"), ("Licensing_Resources", "Licensing Resources")))
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['title']

# the bios that apear on the geomakers.org/team page
class TeamMember(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    picture = models.ImageField(upload_to="images", null=True, blank=True, default=settings.STATIC_URL+"skyshaker/img/user/default.jpg")
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

def updateVideoEmbed(sender, instance, **kwargs):
    instance_url = str(instance.url)
    if 'youtube' in instance_url:
        idOfYoutubeVideo = re.search('(?<=v=)\w+', instance_url).group(0)
        instance.embed = '<iframe width="100%" height="315" src="//www.youtube.com/embed/' + idOfYoutubeVideo + '" frameborder="0" allowfullscreen></iframe>'
    elif 'vimeo' in instance.url:
        idOfVimeoVideo = re.search('(?<=com/)\w+', instance_url).group(0)
        instance.embed = '<iframe src="//player.vimeo.com/video/' + idOfVimeoVideo + '" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'
    post_save.disconnect(updateVideoEmbed, sender=Video)
    instance.save()
    post_save.connect(updateVideoEmbed, sender=Video)

# creates a user profile if a new user exists without one
def createProfile(sender, instance, **kwargs):
    UserProfile.objects.get_or_create(user=instance)

def updateProject(sender, instance, **kwargs):
    # add slug if doesn't exist    
    if instance.slug == "":
        print "slug is '', so we're going to add a new one"
        instance.slug = slugify(instance.title)

    # update rating
    ratingAsString = ""
    for i in range(0,instance.rating):
        ratingAsString += "<span class='star starFilled'>&#9733;</span>"
    for i in range(0,5-instance.rating):
        ratingAsString += "<span class='star starUnfilled'>&#9734;</span>"
    instance.ratingAsString = ratingAsString

    post_save.disconnect(updateProject, sender=Project)
    instance.save()
    post_save.connect(updateProject, sender=Project)

def updateImage(sender, instance, **kwargs):
    # add caption if doesn't exist
    if instance.caption == "":
        print "caption is '', so we're going to add a new one"
        instance.caption = os.path.split(instance.image.url)[1].split('.')[0].split('_')[0]
    post_save.disconnect(updateImage, sender=Image)
    instance.save()
    post_save.connect(updateImage, sender=Image)

# register the signal
post_save.connect(updateVideoEmbed, sender=Video)
post_save.connect(updateProject, sender=Project)
post_save.connect(updateImage, sender=Image)
post_save.connect(createProfile, sender=User)

windwaker/skyshaker/forms.py
from skyshaker.models import Image, Project, UserProfile
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('description', 'location', 'facebook', 'twitter', 'linkedin', 'picture')

class ContributeForm(forms.ModelForm):
    class Meta:
        model = Project
#        fields = ('typeOfProject', 'title', 'abstract', 'location', 'images', 'videos', 'links', 'related')
        fields = ('typeOfProject', 'title', 'abstract', 'location')

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields =('image', 'caption')

windwaker/skyshaker/templates/skyshaker/donate.html
{% extends "skyshaker/base.html" %}
{% block content %}
<div id="donate-middle">
<h1>Help contribute to a growing GeoMaker platform.</h1>
</br>
    <div id="donate-message">
        <h2>From GeoMakers creator Jared Novick</h2>
        <p>GeoMakers is not Wikipedia.  But, like Wikipedia, we want GeoMakers to be a special place where "we can all go to think, to learn, to share our knowledge with others".  As a 501c3 non-profit, the GeoMakers Foundation seeks to provide www.geomakers.org as a new dimension to the global data commons, which empowers all of us to organize the world's knowledge spatially and temporally - rather than encyclopedically.</p><p>When it comes to certain problems, I strongly believe that you can either make money off of them, or you can solve them.  But, you can't do both.  GeoMakers was conceived of in order to let everyone dedicate to the global data commons their knowledge about how the world has changed over time.  For this to work, people must be secure in their knowledge that their cultural contributions are not subject to commercial influence.</p><p>GeoMakers is a new social venture, and we are still working out the kinks.  If you are happy having a place where you can freely publish your spatio-temporal representations of the world to a global use community, and to easily access such data from others, perhaps you might consider contributing $10, $20, or $40 to support the hosting and operations costs of this global data commons.  Remember, all donations are tax deductible.</p><p>Thanks,</p><p>Jared Novick</p>
    </div>
    <div id="donate-pay">
    <h2>Please make a donation.</h2>
    <div>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="KMYBSHEQH7BHJ">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>
    <h2>Where your donation goes</h2>
    <p>Technology: Servers, bandwith, maintenance, development. GeoMakers is build on open source code and hosted in the cloud, so its growth will be affordable, but will still have costs.</p>
    <p>People: GeoMakers is currently largely a volunteer activity, but its sustainment over time will require full time attention from skilled staff. Your resources will help us develop the appropriate staff capacity.</p>
    <!--<p>PAYPAL VERIFIED ICONS</p>-->
    </div>
</div>
{% endblock %}

windwaker/skyshaker/templates/skyshaker/edit-project.html
{% extends "skyshaker/base.html" %}
{% block content %}
<div id="geodream-middle">
<div class="editproj-header">Edit Your Project</div>
<div class="editproj-panel">

<form id="user_form" method="post" action="/skyshaker/projects/{{project.slug}}/edit" enctype="multipart/form-data">
{% csrf_token %}
    <div class="editproj-panel-left">
        <div class="editproj-part">
            <label for="id_owner">Owner:</label>
            <select id="id_owner" name="owner">
                <option value="{{project.owner.id}}"  selected="selected">{{project.owner}}</option>
                {% for user in users %}
                {% if user != project.owner %}
                <option value="{{user.id}}">{{user}}</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>
        <div class="editproj-part">
            <label for="id_typeOfProject">Type of Project:</label>
            <select id="id_typeOfProject" name="typeOfProject">
                
                <option value="" {% if project.typeOfProject == "" %}selected="selected"{% endif %}>---------</option>
                <option value="GeoDream" {% if project.typeOfProject == "GeoDream" %}selected="selected"{% endif %}>GeoDream</option>
                <option value="GeoRecipe" {% if project.typeOfProject == "GeoRecipe" %}selected="selected"{% endif %}>GeoRecipe</option>
                <option value="GeoBoost" {% if project.typeOfProject == "GeoBoost" %}selected="selected"{% endif %}>GeoBoost</option>
            </select>
        </div>        
        <div class="editproj-part">
            <label for="id_title">Name your GeoDream:</label>
            <input id="id_title" maxlength="60" name="title" type="text" value="{{project.title}}">
        </div>
        <div class="editproj-part">
            <label for="id_slug">Nickname for URL | http://geomakers.org/projects/</label>
            <input id="id_slug" maxlength="60" name="slug" type="text" value="{{project.slug}}">
        </div>
        <div class="editproj-part">
            <label for="id_abstract">Abstract/Description:</label> <textarea id="id_abstract" name="abstract">{{project.abstract}}</textarea>
        </div>
        <div class="editproj-part">
            <label for="id_location">GeoDream Location:</label>
            <input id="id_location" maxlength="200" name="location" type="text" value="{{project.location}}">
        </div>
        <div class="editproj-part">
            Images:
            <div id="containerOfImages">
                {% for image in project.images.all %}
                <div class="imageBlock">
                    <div class="imageInputWrapper">
                        <input type="file" name="imageInput_{{forloop.counter0}}" class="imageInput" id="imageInput_{{forloop.counter0}}">
                    </div>
                    <div class="imageImgWrapper">
                        <img src="{{image.image.url}}" alt="image" id="imageImg_{{forloop.counter0}}"/>
                    </div>
                    <div class="imageCaptionWrapper">
                        <input type="text" name="image_caption"  value="{{image.caption}}">
                    </div>
                </div>
                {% endfor %}
            </div>
            <button type="button" id="clickToAddImage">Click here to add an Image</button>
        </div>
        <div class="editproj-part">
            <label for="id_videos">Videos:</label>
            <table id="tableOfVideos">
            <thead><tr><th>Title</th><th>URL/Website Address</th></tr></thead>
            <tbody>
            {% for video in project.videos.all %}
            <tr>
            <td><input type="text" name="video_title"  value="{{video.title}}"></td>
            <td><input type="text" name="video_url" value="{{video.url}}"></td>
            {% endfor %}
            </tbody></table>
            <button type="button" id="clickToAddVideo">Click here to add a Video</button>
        </div>
        <div class="editproj-part">
            <label for="id_links">Links:</label>
            <table id="tableOfLinks">
            <thead><tr><th>Title</th><th>URL/Website Address</th></tr></thead>
            <tbody>
            {% for link in project.links.all %}
            <tr>
            <td><input type="text" name="link_title" value="{{link.title}}"></td>
            <td><input type="text" name="link_url" value="{{link.url}}"></td>
            </tr>
            {% endfor %}
            </tbody></table>
            <button type="button" id="clickToAddLink">Click here to add a Link</button>
        </div>
        <div class="submit-part">
        <label for="id_related">Related:</label><select multiple="multiple" id="id_related">
            {% for related in project.related.all %}
                <option value="{{related.id}}" selected>{{related.title}}</option>
            {% endfor %}
            {% for proj in projects %}
                {% if proj not in project.related.all %}
                <option value="{{proj.id}}">{{proj.title}}</option>
                {% endif %}
            {% endfor %}
        </select>
        </div>
    </div>
    <input type="submit" name="submit" value="Submit" />
</form>
</div>
</div>
<script>
// add link on button click
function addLink(){
    console.log("starting addLink");
    var tableOfLinks = document.getElementById("tableOfLinks");
    var row = tableOfLinks.insertRow(-1);

    var cellTitle = row.insertCell(0);
    var inputTitle = document.createElement("input");
    inputTitle.setAttribute("type", "text");
    inputTitle.setAttribute("name", "link_title");
    cellTitle.appendChild(inputTitle);

    var cellUrl = row.insertCell(1);
    var inputUrl = document.createElement("input");
    inputUrl.setAttribute("type", "text");
    inputUrl.setAttribute("name", "link_url");
    cellUrl.appendChild(inputUrl);
    console.log("finishing addLink");
}

document.getElementById("clickToAddLink").addEventListener("click", addLink);
</script>
<script>
// add video on button click
function addVideo(){
    console.log("starting addVideo");
    var tableOfVideos = document.getElementById("tableOfVideos");
    var row = tableOfVideos.insertRow(-1);

    var cellTitle = row.insertCell(0);
    var inputTitle = document.createElement("input");
    inputTitle.setAttribute("type", "text");
    inputTitle.setAttribute("name", "video_title");
    cellTitle.appendChild(inputTitle);

    var cellUrl = row.insertCell(1);
    var inputUrl = document.createElement("input");
    inputUrl.setAttribute("type", "text");
    inputUrl.setAttribute("name", "video_url");
    cellUrl.appendChild(inputUrl);
    console.log("finishing addVideo");
}

document.getElementById("clickToAddVideo").addEventListener("click", addVideo);
</script>
<script>
// add image if button clicked
function addImage(){
    console.log("starting addImage");
    containerOfImages = document.getElementById("containerOfImages");
    imageBlocks = document.getElementsByClassName("imageBlock");
    numberOfImageBlocks = imageBlocks.length;
    index = numberOfImageBlocks;
    imageBlock = document.createElement("div");
    imageBlock.setAttribute("class", "imageBlock");
    imageBlock.innerHTML = '<div class="imageInputWrapper"><input type="file" name="imageInput_' + index + '" class="imageInput" id="imageInput_' + index + '"></div><div class="imageImgWrapper"><img class="editproj-image-img" src="{{image.image.url}}" alt="image" id="imageImg_' + index + '"></div><div class="imageCaptionWrapper"><input type="text" name="image_caption" value="{{image.caption}}"></div>'
    containerOfImages.appendChild(imageBlock);
    console.log("finishing addImage");

    // updating arrayOfImageInputs
    arrayOfImageInputs = document.getElementsByClassName("imageInput");
    addEventListenersToImageInputs();
}

document.getElementById("clickToAddImage").addEventListener("click", addImage);
</script>
<script>
var arrayOfImageBlocks = document.getElementsByClassName("imageBlock");
var arrayOfImageInputs = document.getElementsByClassName("imageInput");

//display preview image
function readURL(input) {
    console.log("starting readURL");
    indexNumber = input.id.substring(11);
    console.log("index number is " + indexNumber);
    console.log("index class is " + input.className);
    
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            document.getElementById("imageImg_"+indexNumber).src = e.target.result;
        }

        reader.readAsDataURL(input.files[0]);
    }
    
    console.log("finishing readURL");
}

function addEventListenersToImageInputs(){
    console.log("starting addEventListenersToImageInputs");
    arrayOfImageInputs = document.getElementsByClassName("imageInput");
    console.log(arrayOfImageInputs);
    for (var i = 0; i < arrayOfImageInputs.length; i++)
    {
        arrayOfImageInputs[i].addEventListener("change", function(){
            readURL(this);
        });
    }
    console.log("finishing addEventListenersToImageInputs");
}
addEventListenersToImageInputs();

</script>
<script>
// script that make sure people add titles and urls for all the videos, unless both blank
// script that makes sure people specify an owner
</script>
{% endblock %}

windwaker/skyshaker/templates/skyshaker/footer.html
{% load staticfiles %}
        <article id="footer" class="container-fluid">
            <div>
                <div class="col-sm-offset-1 col-sm-2">
                    <input type="radio" id="footer-button-about" name="footer-button">
                    <label for="footer-button-about"><h4 class="footer-text">About</h4></label>
                    <a href="mailto:info@geomakers.org"><h5 class="footer-text">Contact</h5></a>
                    <a href={% url 'team' %}><h5 class="footer-text">Team</h5></a>
                    <a href={% url 'donate' %}><h5 class="footer-text">Donate</h5></a>
                    <a href={% url 'resources' %}><h5 class="footer-text">Resources</h5></a>
                    <a href={% url 'index' %}><h5 class="footer-text">What is GeoMakers?</h5></a>
                </div>
                <div class="col-sm-2">
                    <input type="radio" id="footer-button-contributors" name="footer-button">
                    <label for="footer-button-contributors"><h4 class="footer-text">Contributors</h4></label>
                    <a href={% url 'contribute' %}><h5 class="footer-text">Geo Dreamers</h5></a>
                    <a href={% url 'contribute' %}><h5 class="footer-text">Geo Makers</h5></a>
                    <a href={% url 'contribute' %}><h5 class="footer-text">Geo Boosters</h5></a>
                    <a href={% url 'contribute' %}><h5 class="footer-text">Geo Contests</h5></a>
                </div>
                <div class="col-sm-2">
                    <input type="radio" id="footer-button-support" name="footer-button">
                    <label for="footer-button-support"><h4>Help</h4></label>
                    <a href=""><h5 class="footer-text">Terms of Use</h5></a>
                    <a href=""><h5 class="footer-text">Privacy Policy</h5></a>
                    <a href="mailto:support@geomakers.org"><h5 class="footer-text">Support</h5></a>
                    <a href={% url 'community' %}><h5 class="footer-text">Community Guidelines</h5></a>
                </div>
                <div class="col-sm-2">
                    <input type="radio" id="footer-button-connect" name="footer-button">
                    <label for="footer-button-connect"><h4>Connect</h4></label>
                    <a href="https://www.facebook.com/GeoMakerRevolution"><h5 class="footer-text">Facebook</h5></a>
                    <a href="https://twitter.com/geomakers"><h5 class="footer-text">Twitter</h5></a>
                    <a href="https://instagram.com/geomakers"><h5 class="footer-text">Instagram</h5></a>
                    <a href="https://www.linkedin.com/company/geomakers"><h5 class="footer-text">LinkedIn</h5></a>
                    <a href=""><h5 class="footer-text">YouTube</h5></a>
                    <a href="https://vine.co/u/1081304182532861952"><h5 class="footer-text">Vine</h5></a>
                </div>
                <div class="col-sm-offset-1 col-sm-10" style="border-top:1px solid white">
                    <h4>GeoMakers copyright 2014</h4>
                </div>
            </div>
        </article>

windwaker/skyshaker/templates/skyshaker/geodream.html
{% extends "skyshaker/base.html" %}
{% block content %}
<div id="geodream-middle">
<div class="submit-header">Share Your GeoDream</div>
<div class="submit-panel">
<form id="user_form" method="post" action="/skyshaker/geodream/" enctype="multipart/form-data">
{% csrf_token %}
    <div class="submit-panel-left">
        <div class="submit-part">
            <label for="id_title">Name your GeoDream:</label>
            <input id="id_title" maxlength="60" name="title" type="text">
        </div>
        <div class="submit-part">
            <label for="id_abstract">Tell us about your GeoDream:</label> <textarea id="id_abstract" name="abstract" rows="5"></textarea>
        </div>
        <div class="submit-part">
            <label for="id_location">GeoDream Location:</label>
            <input id="id_location" maxlength="200" name="location" type="text">
        </div>
        <div class="submit-part">
            <label for="id_images">GeoDream Images:</label>
            <input id="id_images" name="images" type="file" multiple>
        </div>
        <div class="submit-part">
            <label for="id_videos">Videos:</label>
            <textarea id="id_videos" name="images" rows="5" multiple></textarea>
        </div>
        <div class="submit-links">
            <label for="id_links">Links:</label>
            <textarea id="id_links" name="images" rows="5" multiple></textarea>
        </div>
    </div>
    <input type="submit" name="submit" value="Submit" />
</form>
</div>
</div>
{% endblock %}

windwaker/skyshaker/templates/skyshaker/georecipes.html
{% extends "skyshaker/base.html" %}
{% block content %}
{% load staticfiles %}
<div id="georecipes-middle">    
    <article id="banner">
        <div class="row">
            <div class="col-sm-12">
                <h1>GeoMakers</h1>
                <h3>Lorem ipsum dolor sit amet</h3>
            </div>
        </div>
    </article>
    <article id="geodream-gallery">
        <section id="demo">
            <article class="white-panel">
                <div id="newrecipe"><h1><a href="geomake_form.html">Start a new GeoMaker Recipe</a></h1></div>
            </article>
            {% for georecipe in georecipes %}
            <article class="white-panel"> <img class="georecipe-img" src="{% if georecipe.images.all.0.image.url %}{{ georecipe.images.all.0.image.url }}{% else %}{% static 'skyshaker/img/project/GeoRecipe.png' %}{% endif %}" alt="ALT">
                <h1><a href={% url 'project' georecipe.slug %}></a></h1>
                <h5>{{ georecipe.title }}</h5>
                {% if georecipe.abstract %}<p>{{georecipe.abstract}}</p>{% endif %}
                <div class="row">
                    <div class="col-sm-offset-3">
                        <button class="btn btn-make btn-md" data-toggle="tooltip" data-original-title="Coming soon."> 15 likes</button>
                        <button class="btn btn-boost btn-md" data-toggle="tooltip" data-original-title="Coming soon."> boost</button>
                    </div>
                </div>
            </article>
            {% endfor %}
        </section>
    </article>
</div>
{% endblock %}

windwaker/skyshaker/templates/skyshaker/team.html
{% extends "skyshaker/base.html" %}
{% load staticfiles %}
{% block content %}

{% endblock %}